---
title: "Yeti 3"
output:
  pdf_document: default
  html_notebook: default
---

```{r}
library(tidyverse)
```


# Horizontal

```{r}
fov <- 40 # field of view

D_yeti3 <- read_csv("Brightness_H.csv", 
                    col_names = c("x", "bright_L", "bright_R", "bright_diff"),
                    col_types = cols(
                      x = col_double(),
                      bright_L = col_double(),
                      bright_R = col_double(),
                      bright_diff = col_double()
                    )) %>% 
  mutate(angle = x/fov)
```


```{r}
D_yeti3 %>% 
  ggplot(aes(y = angle)) +
  geom_point(aes(x = bright_L, col = "Left")) +
  geom_point(aes(x = bright_R, col = "Right")) +
  geom_point(aes(x = bright_diff, col = "diff")) +
  geom_smooth(aes(x = bright_L, col = "Left")) +
  geom_smooth(aes(x = bright_R, col = "Right")) +
  geom_smooth(aes(x = bright_diff, col = "diff")) +
  labs(col = "Frame")
```

```{r}
M_0 <- lm(x ~ bright_L * bright_R, data = D_yeti3)
M_1 <- lm(x ~ bright_L + bright_R, data = D_yeti3)
M_2 <- lm(x ~ bright_diff, data = D_yeti3)
M_3 <- lm(x ~ bright_L, data = D_yeti3)
M_4 <- lm(x ~ bright_R, data = D_yeti3)

AIC(M_0, M_1, M_2, M_3) %>% 
  arrange(AIC)
```


## Vertical

```{r}
fov <- 40 # field of view

D_yeti3 <- read_csv("Brightness_V.csv", 
                    col_names = c("x", "bright_T", "bright_B", "bright_diff"),
                    col_types = cols(
                      x = col_double(),
                      bright_T = col_double(),
                      bright_B = col_double(),
                      bright_diff = col_double()
                    )) %>% 
  mutate(angle = x/fov)
```


```{r}
D_yeti3 %>% 
  ggplot(aes(y = angle)) +
  geom_point(aes(x = bright_T, col = "Top")) +
  geom_point(aes(x = bright_B, col = "Bottom")) +
  geom_point(aes(x = bright_diff, col = "diff")) +
  geom_smooth(aes(x = bright_T, col = "Top")) +
  geom_smooth(aes(x = bright_B, col = "Bottom")) +
  geom_smooth(aes(x = bright_diff, col = "diff")) +
  labs(col = "Frame")
```

```{r}
M_0 <- lm(x ~ bright_T * bright_B, data = D_yeti3)
M_1 <- lm(x ~ bright_T + bright_B, data = D_yeti3)
M_2 <- lm(x ~ bright_diff, data = D_yeti3)
M_3 <- lm(x ~ bright_T, data = D_yeti3)
M_4 <- lm(x ~ bright_B, data = D_yeti3)

AIC(M_0, M_1, M_2, M_3) %>% 
  arrange(AIC)
```



